---
title: ""
format:
  html:
    fig-width: 9
    fig-height: 5
    fig-asp: 0.8
    dpi: 300
    echo: FALSE
    message: FALSE
    warning: FALSE
---

```{r}

library(tidyverse)
library(ggthemes)

basel = read_csv('1_Data/taxation.csv')

```

```{r}


my_plot = basel %>%
  
  # sort by income and factor quarter
  arrange(year, income_median) %>% 
  mutate(quarter = as_factor(quarter)) %>% 
  
  # original code
  ggplot(aes(x = year, y = income_median, col = quarter)) +
  geom_line() + geom_point() +
  theme_minimal() +
  theme(
    legend.position = "bottom",
    legend.title = element_blank(),
    legend.text = element_text(size=7)) + 
  scale_color_viridis_d() 

my_plot <- 
my_plot  +
  labs(x = "Year", y = "Median income")


```

````markdown
> The name of Basel is first recorded as Basilia in the 3rd century, 
at the time referring to the Roman castle. 
>> Quotes can be nested.
````
> The name of Basel is first recorded as Basilia in the 3rd century, at the time referring to the Roman castle. 

>> Quotes can be nested.

```{r echo = FALSE}
#| fig-cap: "Figure 1: Inequality development by quarter from 2001 to 2017."
my_plot

```