project:
  type: website

website:
  title: "Our UniBE website"
  navbar:
    right:
      - href: index.qmd
      - text: "Home"
      - about.qmd 
    tools:
      - icon: twitter-x
        href: https://twitter.com
      - icon: instagram
        href: https://instagram.com
    background: primary
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



